# Generated by Django 5.1.6 on 2025-02-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appoinment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='status',
            field=models.CharField(choices=[('visited', 'Visited'), ('not visited', 'Not Visited')], default='not visited', max_length=20),
        ),
    ]
